spring:
  profiles:
    active: "loadInitialData"
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  mail:
    host: "smtp.mailtrap.io"
    port: 587
    username: "79a2693eeef9a8"
    password: "62afe2726b30b1"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true